#!/usr/bin/env bash
set -euo pipefail

# Standalone installer for users who install WSA from a public URL instead of
# cloning the source checkout. It creates a persistent data directory, a
# private virtual environment, an environment file, and the default iCloud
# capture directory on macOS.

WSA_PYTHON_BIN="${WSA_PYTHON_BIN:-python3}"
WSA_PACKAGE="${WSA_PACKAGE:-wechat-social-assistant>=1.4.4}"
NO_SHELL_RC=0
USE_ICLOUD="${WSA_USE_ICLOUD:-0}"

case "$(uname -s)" in
  Darwin)
    WSA_DEFAULT_HOME="${HOME}/Library/Application Support/wechat-social-assistant"
    WSA_DEFAULT_CAPTURES="${HOME}/Library/Mobile Documents/com~apple~CloudDocs/codex/wechat-social-assistant/data/captures"
    ;;
  *)
    WSA_DEFAULT_HOME="${HOME}/.local/share/wechat-social-assistant"
    WSA_DEFAULT_CAPTURES=""
    ;;
esac

WSA_HOME="${WSA_HOME:-$WSA_DEFAULT_HOME}"
WSA_DATA_DIR="${WSA_DATA_DIR:-$WSA_HOME/data}"
WSA_DB="${WSA_DB:-$WSA_DATA_DIR/social.db}"
WSA_VENV_DIR="${WSA_VENV_DIR:-$WSA_HOME/venv}"
WSA_BIN_DIR="${WSA_BIN_DIR:-$HOME/.local/bin}"
WSA_ENV_FILE="${WSA_ENV_FILE:-$WSA_HOME/env.sh}"

usage() {
  cat <<'EOF'
Usage: install-user.sh [options]

Install the published WSA package without requiring a source checkout.

Options:
  --python PATH       Python 3.11+ executable (default: python3)
  --icloud             Use the conventional iCloud Drive capture directory on macOS
  --no-shell-rc      Do not add the generated environment file to .zprofile/.bash_profile
  -h, --help         Show this help

Environment overrides:
  WSA_HOME, WSA_DATA_DIR, WSA_DB, WSA_VENV_DIR, WSA_BIN_DIR,
  WSA_ENV_FILE, WSA_CAPTURES_DIR, WSA_PACKAGE, WSA_SHELL_RC, WSA_USE_ICLOUD
EOF
}

while (($# > 0)); do
  case "$1" in
    --python)
      (($# >= 2)) || { echo "--python requires a path" >&2; exit 2; }
      WSA_PYTHON_BIN="$2"
      shift 2
      ;;
    --no-shell-rc)
      NO_SHELL_RC=1
      shift
      ;;
    --icloud)
      USE_ICLOUD=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

command -v "$WSA_PYTHON_BIN" >/dev/null 2>&1 || {
  echo "Python executable not found: $WSA_PYTHON_BIN" >&2
  exit 1
}

"$WSA_PYTHON_BIN" - <<'PY'
import sys

if sys.version_info < (3, 11):
    raise SystemExit(
        f"WSA requires Python 3.11 or newer; found {sys.version_info.major}.{sys.version_info.minor}"
    )
print(f"Using Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
PY

if [[ -z "${WSA_CAPTURES_DIR:-}" ]]; then
  if [[ "$USE_ICLOUD" -eq 1 && -n "$WSA_DEFAULT_CAPTURES" && -d "$(dirname "$WSA_DEFAULT_CAPTURES")" ]]; then
    WSA_CAPTURES_DIR="$WSA_DEFAULT_CAPTURES"
  else
    WSA_CAPTURES_DIR="$WSA_DATA_DIR/captures"
  fi
fi

mkdir -p "$WSA_DATA_DIR" "$WSA_CAPTURES_DIR" "$WSA_BIN_DIR" "$WSA_HOME"

if [[ ! -x "$WSA_VENV_DIR/bin/python" ]]; then
  if [[ -e "$WSA_VENV_DIR" ]]; then
    echo "Virtual environment path exists but is not usable: $WSA_VENV_DIR" >&2
    exit 1
  fi
  echo "Creating WSA virtual environment: $WSA_VENV_DIR"
  "$WSA_PYTHON_BIN" -m venv "$WSA_VENV_DIR"
fi

WSA_VENV_PYTHON="$WSA_VENV_DIR/bin/python"
echo "Installing $WSA_PACKAGE..."
"$WSA_VENV_PYTHON" -m pip install --disable-pip-version-check --no-input --upgrade "$WSA_PACKAGE"

WSA_CLI="$WSA_VENV_DIR/bin/wsa"
"$WSA_CLI" --db "$WSA_DB" init >/dev/null
"$WSA_CLI" --db "$WSA_DB" captures-dir "$WSA_CAPTURES_DIR" --create >/dev/null

# Keep the environment file private: it contains local filesystem paths and
# is intended to be sourced by the user's shell, not checked into a project.
umask 077
{
  printf '# Generated by WeChat Social Assistant.\n'
  printf 'export WSA_HOME=%q\n' "$WSA_HOME"
  printf 'export WSA_DATA_DIR=%q\n' "$WSA_DATA_DIR"
  printf 'export WSA_DB=%q\n' "$WSA_DB"
  printf 'export WSA_VENV_DIR=%q\n' "$WSA_VENV_DIR"
  printf 'export WSA_CAPTURES_DIR=%q\n' "$WSA_CAPTURES_DIR"
  printf 'export WSA_ALLOWED_ROOT=%q\n' "$WSA_HOME"
  printf 'export PATH=%q:%q:"$PATH"\n' "$WSA_BIN_DIR" "$WSA_VENV_DIR/bin"
} > "$WSA_ENV_FILE"

SHELL_RC="${WSA_SHELL_RC:-}"
if [[ -z "$SHELL_RC" ]]; then
  case "${SHELL##*/}" in
    zsh) SHELL_RC="${ZDOTDIR:-$HOME}/.zprofile" ;;
    bash) SHELL_RC="$HOME/.bash_profile" ;;
  esac
fi
if [[ "$NO_SHELL_RC" -eq 0 && -n "$SHELL_RC" ]]; then
  mkdir -p "$(dirname "$SHELL_RC")"
  touch "$SHELL_RC"
  if ! grep -Fq "$WSA_ENV_FILE" "$SHELL_RC"; then
    {
      printf '\n# WeChat Social Assistant\n'
      printf 'source %q\n' "$WSA_ENV_FILE"
    } >> "$SHELL_RC"
  fi
fi

cat <<EOF

WSA installation complete.

Data directory:   $WSA_DATA_DIR
Database:         $WSA_DB
Screenshots:      $WSA_CAPTURES_DIR
Environment file: $WSA_ENV_FILE

Open a new terminal (or run: source $(printf '%q' "$WSA_ENV_FILE")), then:
  wsa status
  wsa watch
  wsa ui --no-browser

Stop capture:
  wsa stop-watch
EOF
